export const DEPT_EN: Record<string, string> = {
  "기계공학부": "Department of Mechanical Engineering",
  "산업경영공학과": "Department of Industrial & Management Engineering",
  "원자력공학과": "Department of Nuclear Engineering",
  "화학공학과": "Department of Chemical Engineering",
  "신소재공학과": "Department of Advanced Materials Engineering",
  "사회기반시스템공학과": "Department of Civil & Environmental Engineering",
  "건축공학과": "Department of Architectural Engineering",
  "환경학및환경공학과": "Department of Environmental Science & Engineering",
  "건축학과": "Department of Architecture",
  "산업디자인학과": "Department of Industrial Design",
  "시각디자인학과": "Department of Visual Communication Design",
  "환경조경디자인학과": "Department of Environmental Landscape Design",
  "디지털콘텐츠학과": "Department of Digital Contents",
  "도예학과": "Department of Ceramic Arts",
  "연극영화학화학과": "Department of Theater & Film",
  "PostModern음악과": "Department of PostModern Music",
  "컴퓨터공학과": "Department of Computer Science & Engineering",
  "소프트웨어융합학과": "Department of Software Convergence",
  "인공지능학과": "Department of Artificial Intelligence",
};
